# Generated by Django 4.0.4 on 2022-05-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_event_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
