# Generated by Django 4.0.4 on 2022-05-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_rename_news_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
    ]
